-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--Mena Nguyen C20418324 TU858
--Justine Langridge C20333476 TU858

DROP TABLE booking CASCADE CONSTRAINTS;

DROP TABLE guest CASCADE CONSTRAINTS;

DROP TABLE maincustomer CASCADE CONSTRAINTS;

DROP TABLE restaurant CASCADE CONSTRAINTS;

DROP TABLE server CASCADE CONSTRAINTS;

DROP TABLE staff CASCADE CONSTRAINTS;

DROP TABLE "Table" CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE booking (
    book_id               NUMBER NOT NULL,
    book_time             TIMESTAMP,
    book_date             DATE,
    book_duration         NUMBER,
    amount_of_people      NUMBER,
    book_type             VARCHAR2(6),
    book_fine             NUMBER,
    restaurant_rest_id    NUMBER NOT NULL,
    table_table_id        NUMBER NOT NULL,
    maincustomer_cust_id  NUMBER NOT NULL
    
);


ALTER TABLE booking ADD CONSTRAINT booking_pk PRIMARY KEY ( book_id );

CREATE TABLE guest (
    guest_name            VARCHAR2(30),
    guest_email           VARCHAR2(30),
    guest_phone           NUMBER,
    guest_address         VARCHAR2(50),
    booking_book_id       NUMBER NOT NULL,
    guest_check           VARCHAR2(15),
    maincustomer_cust_id  NUMBER NOT NULL
);

ALTER TABLE guest
    ADD CONSTRAINT guest_ck_check CHECK ( guest_check = 'arrived'
                                          OR guest_check = 'not' OR guest_check = 'NULL' );

CREATE TABLE maincustomer (
    cust_id          NUMBER NOT NULL,
    cust_name        VARCHAR2(30),
    cust_address     VARCHAR2(50),
    cust_email       VARCHAR2(30),
    cust_age         NUMBER
);

ALTER TABLE maincustomer ADD CONSTRAINT maincustomer_ck_age CHECK ( cust_age >= 18 );

ALTER TABLE maincustomer ADD CONSTRAINT maincustomer_pk PRIMARY KEY ( cust_id );

CREATE TABLE restaurant (
    rest_id       NUMBER NOT NULL,
    rest_address  VARCHAR2(50),
    rest_phone    NUMBER
);

ALTER TABLE restaurant ADD CONSTRAINT resturant_pk PRIMARY KEY ( rest_id );

CREATE TABLE server (
    staff_staff_id   NUMBER NOT NULL,
    booking_book_id  NUMBER NOT NULL
);

ALTER TABLE server ADD CONSTRAINT staffbook_pk PRIMARY KEY ( staff_staff_id,
                                                             booking_book_id );

CREATE TABLE staff (
    staff_id            NUMBER NOT NULL,
    staff_name          VARCHAR2(30),
    staff_address       VARCHAR2(50),
    staff_phone         NUMBER,
    staff_email         VARCHAR2(30),
    staff_dob           DATE,
    staff_start_date    DATE,
    restaurant_rest_id  NUMBER NOT NULL,
    staff_role          VARCHAR2(9)
);

ALTER TABLE staff ADD CONSTRAINT staff_ck_email CHECK ( staff_email LIKE '%@burgershack.com' );

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( staff_id );

ALTER TABLE staff
    ADD CONSTRAINT staff_ck_role CHECK ( staff_role = 'manager'
                                          OR staff_role = 'waiter' );

CREATE TABLE "Table" (
    table_id        NUMBER NOT NULL,
    table_type      VARCHAR2(6),
    table_location  VARCHAR2(10)
);

ALTER TABLE "Table" ADD CONSTRAINT table_pk PRIMARY KEY ( table_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_maincustomer_fk FOREIGN KEY ( maincustomer_cust_id )
        REFERENCES maincustomer ( cust_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_restaurant_fk FOREIGN KEY ( restaurant_rest_id )
        REFERENCES restaurant ( rest_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_table_fk FOREIGN KEY ( table_table_id )
        REFERENCES "Table" ( table_id );

ALTER TABLE guest
    ADD CONSTRAINT guest_booking_fk FOREIGN KEY ( booking_book_id )
        REFERENCES booking ( book_id );

ALTER TABLE guest
    ADD CONSTRAINT guest_maincustomer_fk FOREIGN KEY ( maincustomer_cust_id )
        REFERENCES maincustomer ( cust_id );

ALTER TABLE staff
    ADD CONSTRAINT staff_restaurant_fk FOREIGN KEY ( restaurant_rest_id )
        REFERENCES restaurant ( rest_id );

ALTER TABLE server
    ADD CONSTRAINT staffbook_booking_fk FOREIGN KEY ( booking_book_id )
        REFERENCES booking ( book_id );

ALTER TABLE server
    ADD CONSTRAINT staffbook_staff_fk FOREIGN KEY ( staff_staff_id )
        REFERENCES staff ( staff_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0